[project]
name = "wiktionary-de-parser"
version = "0.14.2"
description = "Extracts data from German Wiktionary dump files."
authors = [{ name = "Gregor Weichbrodt", email = "gregorweichbrodt@gmail.com" }]
requires-python = ">=3.11,<4"
readme = "README.md"
license = "MIT"
keywords = [
    "wiktionary",
    "xml",
    "parser",
    "data-extraction",
    "german",
    "nlp",
]
classifiers = [
    "Programming Language :: Python :: 3.7",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Natural Language :: German",
    "Topic :: Text Processing :: Markup :: XML",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
dependencies = [
    "lxml>=5.1.0,<6",
    "mwparserfromhell>=0.6.6,<0.7",
    "pydantic>=2.6.0,<3",
    "requests>=2.31.0,<3",
    "tqdm>=4.66.1,<5",
    "wikitextparser>=0.56.2,<0.57",
]

[project.urls]
Homepage = "https://github.com/gambolputty/wiktionary-de-parser"
Repository = "https://github.com/gambolputty/wiktionary-de-parser"
"Bug Tracker" = "https://github.com/gambolputty/wiktionary-de-parser/issues"

[dependency-groups]
dev = [
    "ipykernel>=6.29.0,<7",
    "ipywidgets>=8.1.5,<9",
    "pytest>=7.1.2,<8",
    "ruff>=0.14.5,<0.15",
]

[tool.uv]
default-groups = "all"

[tool.uv.build-backend]
module-name = "wiktionary_de_parser"
module-root = ""
source-include = [
    "CHANGELOG.md",
    "LICENSE.txt",
]

[build-system]
requires = ["uv_build>=0.9.16,<0.10.0"]
build-backend = "uv_build"

[tool.ruff]
extend-exclude = [".vscode"]
line-length = 80

[tool.ruff.lint]
select = ["E", "F", "B", "W"]

[tool.ruff.lint.pycodestyle]
max-doc-length = 150
